/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as CuentasPorPagarRouteImport } from './routes/cuentas-por-pagar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FinanzasRouteImport } from './routes/finanzas'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as ModelosRouteImport } from './routes/modelos'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as PosRouteImport } from './routes/pos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as RecambioRouteImport } from './routes/recambio'
import { Route as ReparacionRouteImport } from './routes/reparacion'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ServiciosTallerRouteImport } from './routes/servicios-taller'
import { Route as TallerRouteImport } from './routes/taller'
import { Route as VariablesRouteImport } from './routes/variables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentasPorPagarRoute = CuentasPorPagarRouteImport.update({
  id: '/cuentas-por-pagar',
  path: '/cuentas-por-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRoute = FinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelosRoute = ModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const RecambioRoute = RecambioRouteImport.update({
  id: '/recambio',
  path: '/recambio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReparacionRoute = ReparacionRouteImport.update({
  id: '/reparacion',
  path: '/reparacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosTallerRoute = ServiciosTallerRouteImport.update({
  id: '/servicios-taller',
  path: '/servicios-taller',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerRoute = TallerRouteImport.update({
  id: '/taller',
  path: '/taller',
  getParentRoute: () => rootRouteImport,
} as any)
const VariablesRoute = VariablesRouteImport.update({
  id: '/variables',
  path: '/variables',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cuentas-por-pagar': typeof CuentasPorPagarRoute
  '/dashboard': typeof DashboardRoute
  '/finanzas': typeof FinanzasRoute
  '/inventario': typeof InventarioRoute
  '/marcas': typeof MarcasRoute
  '/modelos': typeof ModelosRoute
  '/pagos': typeof PagosRoute
  '/personal': typeof PersonalRoute
  '/pos': typeof PosRoute
  '/proveedores': typeof ProveedoresRoute
  '/recambio': typeof RecambioRoute
  '/reparacion': typeof ReparacionRoute
  '/servicios': typeof ServiciosRoute
  '/servicios-taller': typeof ServiciosTallerRoute
  '/taller': typeof TallerRoute
  '/variables': typeof VariablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cuentas-por-pagar': typeof CuentasPorPagarRoute
  '/dashboard': typeof DashboardRoute
  '/finanzas': typeof FinanzasRoute
  '/inventario': typeof InventarioRoute
  '/marcas': typeof MarcasRoute
  '/modelos': typeof ModelosRoute
  '/pagos': typeof PagosRoute
  '/personal': typeof PersonalRoute
  '/pos': typeof PosRoute
  '/proveedores': typeof ProveedoresRoute
  '/recambio': typeof RecambioRoute
  '/reparacion': typeof ReparacionRoute
  '/servicios': typeof ServiciosRoute
  '/servicios-taller': typeof ServiciosTallerRoute
  '/taller': typeof TallerRoute
  '/variables': typeof VariablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cuentas-por-pagar': typeof CuentasPorPagarRoute
  '/dashboard': typeof DashboardRoute
  '/finanzas': typeof FinanzasRoute
  '/inventario': typeof InventarioRoute
  '/marcas': typeof MarcasRoute
  '/modelos': typeof ModelosRoute
  '/pagos': typeof PagosRoute
  '/personal': typeof PersonalRoute
  '/pos': typeof PosRoute
  '/proveedores': typeof ProveedoresRoute
  '/recambio': typeof RecambioRoute
  '/reparacion': typeof ReparacionRoute
  '/servicios': typeof ServiciosRoute
  '/servicios-taller': typeof ServiciosTallerRoute
  '/taller': typeof TallerRoute
  '/variables': typeof VariablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/compras'
    | '/cuentas-por-pagar'
    | '/dashboard'
    | '/finanzas'
    | '/inventario'
    | '/marcas'
    | '/modelos'
    | '/pagos'
    | '/personal'
    | '/pos'
    | '/proveedores'
    | '/recambio'
    | '/reparacion'
    | '/servicios'
    | '/servicios-taller'
    | '/taller'
    | '/variables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/compras'
    | '/cuentas-por-pagar'
    | '/dashboard'
    | '/finanzas'
    | '/inventario'
    | '/marcas'
    | '/modelos'
    | '/pagos'
    | '/personal'
    | '/pos'
    | '/proveedores'
    | '/recambio'
    | '/reparacion'
    | '/servicios'
    | '/servicios-taller'
    | '/taller'
    | '/variables'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/compras'
    | '/cuentas-por-pagar'
    | '/dashboard'
    | '/finanzas'
    | '/inventario'
    | '/marcas'
    | '/modelos'
    | '/pagos'
    | '/personal'
    | '/pos'
    | '/proveedores'
    | '/recambio'
    | '/reparacion'
    | '/servicios'
    | '/servicios-taller'
    | '/taller'
    | '/variables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  CuentasPorPagarRoute: typeof CuentasPorPagarRoute
  DashboardRoute: typeof DashboardRoute
  FinanzasRoute: typeof FinanzasRoute
  InventarioRoute: typeof InventarioRoute
  MarcasRoute: typeof MarcasRoute
  ModelosRoute: typeof ModelosRoute
  PagosRoute: typeof PagosRoute
  PersonalRoute: typeof PersonalRoute
  PosRoute: typeof PosRoute
  ProveedoresRoute: typeof ProveedoresRoute
  RecambioRoute: typeof RecambioRoute
  ReparacionRoute: typeof ReparacionRoute
  ServiciosRoute: typeof ServiciosRoute
  ServiciosTallerRoute: typeof ServiciosTallerRoute
  TallerRoute: typeof TallerRoute
  VariablesRoute: typeof VariablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuentas-por-pagar': {
      id: '/cuentas-por-pagar'
      path: '/cuentas-por-pagar'
      fullPath: '/cuentas-por-pagar'
      preLoaderRoute: typeof CuentasPorPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas': {
      id: '/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof FinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelos': {
      id: '/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof ModelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recambio': {
      id: '/recambio'
      path: '/recambio'
      fullPath: '/recambio'
      preLoaderRoute: typeof RecambioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparacion': {
      id: '/reparacion'
      path: '/reparacion'
      fullPath: '/reparacion'
      preLoaderRoute: typeof ReparacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios-taller': {
      id: '/servicios-taller'
      path: '/servicios-taller'
      fullPath: '/servicios-taller'
      preLoaderRoute: typeof ServiciosTallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller': {
      id: '/taller'
      path: '/taller'
      fullPath: '/taller'
      preLoaderRoute: typeof TallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variables': {
      id: '/variables'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof VariablesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  CuentasPorPagarRoute: CuentasPorPagarRoute,
  DashboardRoute: DashboardRoute,
  FinanzasRoute: FinanzasRoute,
  InventarioRoute: InventarioRoute,
  MarcasRoute: MarcasRoute,
  ModelosRoute: ModelosRoute,
  PagosRoute: PagosRoute,
  PersonalRoute: PersonalRoute,
  PosRoute: PosRoute,
  ProveedoresRoute: ProveedoresRoute,
  RecambioRoute: RecambioRoute,
  ReparacionRoute: ReparacionRoute,
  ServiciosRoute: ServiciosRoute,
  ServiciosTallerRoute: ServiciosTallerRoute,
  TallerRoute: TallerRoute,
  VariablesRoute: VariablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
